baseURL = "https://marketing.nextwavesolutions.io"
languageCode = "en-us"
title = "NextWave Marketing"
theme = "hugo-hero-theme"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "Here at NextWave we pride ourselves in utilizing the latest technology to outpace the competition and bring an advantage to our clients."
    meta_og_title = "NextWave Marking"
    meta_og_type = "website"
    meta_og_url = "https://marketing.nextwavesolutions.io"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Here at NextWave we pride ourselves in utilizing the latest technology to outpace the competition and bring an advantage to our clients."
    meta_twitter_card = "summary"
    meta_twitter_site = "@nextwavesllc"
    meta_twitter_creator = "@justyntemme"

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
